### ISSUE TITLE
Can you provide simple example how use it?

### ISSUE THREAD

**Issue by WildEgor** [danocmx/nestjs-socket.io-client#5]
I try to connect with my socket server like this:

app.module.ts

```
import { Module } from '@nestjs/common';
import { SocketIoClientModule } from 'nestjs-socket.io-client';
import { ManagerOptions, SocketOptions } from 'socket.io-client';
import { AppController } from './app.controller';
import { AppService } from './app.service';
import { VlcModule } from './vlc/vlc.module';

@Module({
  imports: [
    VlcModule,
    SocketIoClientModule.forRoot<Partial<ManagerOptions & SocketOptions>>(
      'http://localhost:20000/',
      {
        forceNew: true,
        query: { token: '934ea9cb-f50e-4e1b-8d46-2257ce7fb260' },
      },
    ),
  ],
  controllers: [AppController],
  providers: [AppService],
})
export class AppModule {}
```

app.service.ts

```
import { Injectable, Inject, Logger } from '@nestjs/common';
import {
  SocketIoClientModule,
  OnSocketEvent,
  SOCKET_IO_CLIENT,
} from 'nestjs-socket.io-client';
import { Socket } from 'socket.io-client';
@Injectable()
export class AppService {
  private logger = new Logger('AppService');
  /**
   * Inject the socket instance and use it's methods this way:
   */
  constructor(@Inject(SOCKET_IO_CLIENT) private readonly socket: Socket) {}
  @OnSocketEvent('connect')
  onConnect() {
    this.logger.log('Successfully connected the socket.io server!');
  }
}
```

but still has error:

```
[Nest] 11672  - 09/28/2021, 11:09:56 AM   ERROR [ExceptionHandler] Nest can't resolve dependencies of the SocketIoEventLoader (DiscoveryService, MetadataScanner, ?, SOCKET_IO_CLIENT, SOCKET_OPTIONS). Please 
make sure that the argument Reflector at index [2] is available in the SocketIoClientModule context.

Potential solutions:
- If Reflector is a provider, is it part of the current SocketIoClientModule?
- If Reflector is exported from a separate @Module, is that module imported within SocketIoClientModule?
  @Module({
    imports: [ /* the Module containing Reflector */ ]
  })

Error: Nest can't resolve dependencies of the SocketIoEventLoader (DiscoveryService, MetadataScanner, ?, SOCKET_IO_CLIENT, SOCKET_OPTIONS). Please make sure that the argument Reflector at index [2] is available in the SocketIoClientModule context.

Potential solutions:
- If Reflector is a provider, is it part of the current SocketIoClientModule?
- If Reflector is exported from a separate @Module, is that module imported within SocketIoClientModule?
  @Module({
    imports: [ /* the Module containing Reflector */ ]
  })

    at Injector.lookupComponentInParentModules (D:\_\node_modules\@nestjs\core\injector\injector.js:193:19)        
    at Injector.resolveComponentInstance (D:\_\node_modules\@nestjs\core\injector\injector.js:149:33)
    at resolveParam (D:\_\node_modules\@nestjs\core\injector\injector.js:103:38)
    at async Promise.all (index 2)
    at Injector.resolveConstructorParams (D:\_\node_modules\@nestjs\core\injector\injector.js:118:27)
    at Injector.loadInstance (D:\_\@nestjs\core\injector\injector.js:47:9)
    at Injector.loadProvider (D:\_\node_modules\@nestjs\core\injector\injector.js:69:9)
    at async Promise.all (index 5)
    at InstanceLoader.createInstancesOfProviders (D:\_\node_modules\@nestjs\core\injector\instance-loader.js:44:9) 
    at D:\_\node_modules\@nestjs\core\injector\instance-loader.js:29:13
```

**Comment by danocmx** [comment]
Are you using version 1.0.6?

**Comment by WildEgor** [comment]
@danocmx yes, can you add "example" folder with simple nest project in repo?

**Comment by danocmx** [comment]
Done, [sample](https://github.com/danocmx/nestjs-socket.io-client/tree/master/sample).
